# Configuración básica para un blog Jekyll en GitHub Pages

title: "Blog Astronómico"
description: "Blog de observación astronómica y ciencia"
author: AgusWeb1999

# Tema soportado por GitHub Pages
theme: minima

# Idioma del sitio
lang: es

# Configuración de URL base (útil si usas un custom domain)
baseurl: "" # No cambiar si usas la raíz del repo

# Información de redes sociales (opcional)
twitter_username: "tu_usuario"
github_username: "AgusWeb1999"

# Configuración de comentarios (puedes eliminar si no usas)
comments: false

# Permalink para los posts
permalink: /:year/:month/:day/:title/

# Mostrar el año en el pie de página
show_excerpts: true

# Plugins soportados por GitHub Pages (opcional)
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Excluir archivos/directorios del build
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

# Configuración de colección de posts
collections:
  posts:
    output: true